[package]
name = "peroxide-discord"
version = "0.1.0"
authors = ["Matthieu Felix <matthieufelix@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
lazy_static = "1.4"
peroxide = { path = "../peroxide/" }
regex = "1"
serenity = "0.9"
tokio = {version = "0.3", features = ["time"]}
